In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("bigger_loan_default_dataset.csv")
df.shape

(100, 6)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Income             100 non-null    int64
 1   Age                100 non-null    int64
 2   Employment_Status  100 non-null    object
 3   Credit_Score       100 non-null    int64
 4   Existing_Debt      100 non-null    int64
 5   Default            100 non-null    object
dtypes: int64(4), object(2)
memory usage: 4.8+ KB

In [4]:
df_copy = df.copy()
df_copy.drop_duplicates()
df_copy.shape

(100, 6)

In [5]:
df.isnull().sum()

Income               0
Age                  0
Employment_Status    0
Credit_Score         0
Existing_Debt        0
Default              0
dtype: int64

In [6]:
df.head()

   Income  Age Employment_Status  Credit_Score  Existing_Debt Default
0  146958   28     Self-Employed           534          21056     Yes
1   40795   34          Employed           691           4343      No
2   25860   43        Unemployed           548          14500     Yes
3  128694   41        Unemployed           516          30375     Yes
4  144879   36          Employed           671          10662      No

In [7]:
df = pd.get_dummies(df, columns=["Employment_Status"])

In [8]:
df.head()

,Income,Age,Credit_Score,Existing_Debt,Default,Employment_Status_Employed,Employment_Status_Self-Employed,Employment_Status_Unemployed
0,146958,28,534,21056,Yes,False,True,False
1,40795,34,691,4343,No,True,False,False
2,25860,43,548,14500,Yes,False,False,True
3,128694,41,516,30375,Yes,False,False,True
4,144879,36,671,10662,No,True,False,False

In [9]:
col = ['Employment_Status_Employed','Employment_Status_Self-Employed','Employment_Status_Unemployed']

In [10]:
df[col]=df[col].astype(int)

In [11]:
df.head()

,Income,Age,Credit_Score,Existing_Debt,Default,Employment_Status_Employed,Employment_Status_Self-Employed,Employment_Status_Unemployed
0,146958,28,534,21056,Yes,0,1,0
1,40795,34,691,4343,No,1,0,0
2,25860,43,548,14500,Yes,0,0,1
3,128694,41,516,30375,Yes,0,0,1
4,144879,36,671,10662,No,1,0,0

In [12]:
x=df.drop('Default',axis = 1)
y=df['Default']

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.20,random_state = 42)

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB,BernoulliNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,precision_score,classification_report,confusion_matrix,f1_score

In [16]:
models={
    'regre':LogisticRegression(),
    'knn':KNeighborsClassifier(),
    'nb':GaussianNB(),
    'Nb':BernoulliNB(),
    'tree':DecisionTreeClassifier(),
    'svm':SVC(kernel='rbf')
}

In [17]:
result = []

In [18]:
for name,model in models.items():
    model.fit(x_train_scaled,y_train)
    y_pred = model.predict(x_test_scaled)
    acc = accuracy_score(y_test,y_pred)
    f1 = f1_score(y_test,y_pred,pos_label="Yes")
    result.append({
        'model':name,
        'accuracy':round(acc,4),
        'f1score':round(f1,4)
    })

In [19]:
result

[{'model': 'regre', 'accuracy': 0.9, 'f1score': 0.6667},
 {'model': 'knn', 'accuracy': 0.8, 'f1score': 0.3333},
 {'model': 'nb', 'accuracy': 0.9, 'f1score': 0.5},
 {'model': 'Nb', 'accuracy': 0.75, 'f1score': 0.0},
 {'model': 'tree', 'accuracy': 1.0, 'f1score': 1.0},
 {'model': 'svm', 'accuracy': 0.8, 'f1score': 0.3333}]

In [21]:
import joblib
joblib.dump(models['regre'],'tree_loan.pkl')
joblib.dump(scaler,'scaler.pkl')
joblib.dump(x.columns,'columns.pkl')

['columns.pkl']